[tool.poetry]
name = "paradox-codegen"
version = "0.8.0"
description = ""
license = "MIT"
authors = []
packages = [
    { include = "paradox" }
]
# make sure py.typed files are included when installing via poetry (seutp.py does this differently)
include = ["py.typed"]

[tool.poetry.dependencies]
python = "^3.6"
dataclasses = {version = "^0.7", python = "<3.7"}
# needed for typing_extensions.Literal
typing-extensions = {version = "^3.7.4", python = "<3.8"}

[tool.poetry.dev-dependencies]
mypy = "^0.770"
flake8 = "^3.8.4"
pytest = "^6.2.1"

[build-system]
requires = ["setuptools>=40.0", "wheel", "pytoml"]

