on: [push, pull_request]

jobs:
    linting:
        name: "Linters / Static Checkers"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup python
              uses: actions/setup-python@v2
              with:
                python-version: 3.8
            - run: python -m pip install poetry
            - run: poetry config virtualenvs.create false
            - run: poetry install
            - run: mypy .
            - run: flake8 setup.py paradox

    unit_tests:
      name: "Pytest"
      runs-on: ubuntu-latest
      strategy:
        matrix:
            python-version: [3.6, 3.7, 3.8, 3.9, "3.10"]
      steps:
        - uses: actions/checkout@v2
        - name: Setup python
          uses: actions/setup-python@v2
          with:
            python-version: ${{matrix.python-version}}
        - run: python -m pip install poetry
        - run: poetry config virtualenvs.create false
        - run: poetry install
        - run: py.test
