on: [push, pull_request]

jobs:
    linting:
        name: "Linters"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup python
              uses: actions/setup-python@v2
              with:
                python-version: 3.8
            - run: python -m pip install poetry
            - run: poetry install
            - run: flake8 setup.py paradox
